name: Chatbot Backend CI/CD

on:
  push:
    branches: [ "chatbot" ]
    paths:
      - "chatbot/backend/**"
      - ".github/workflows/chatbot-backend-cicd.yml"
      - "deployments/chatbot-backend-deployment.yaml"
  pull_request:
    branches: [ "chatbot" ]
    paths:
      - "chatbot/backend/**"

env:
  ACR_NAME: "kt16big"                         # ACR 이름
  IMAGE_NAME: "chatbot-backend"               # 이미지 리포지토리 이름
  WORKING_DIR: "chatbot/backend"              # Docker 컨텍스트 루트
  AKS_CLUSTER_NAME: "kt16big-aks"             # AKS 클러스터 이름
  AKS_RESOURCE_GROUP: "kt16big"               # AKS 리소스 그룹
  DEPLOYMENT_FILE: "deployments/chatbot-backend-deployment.yaml"

jobs:
  build-and-push-to-acr:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: get_sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR (az acr login)
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.get_sha.outputs.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

  deploy-to-aks:
    name: Deploy to AKS
    needs: build-and-push-to-acr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Substitute IMAGE_TAG and Deploy to AKS
        env:
          IMAGE_TAG: ${{ needs.build-and-push-to-acr.outputs.image_tag }}
        run: |
          envsubst < ${{ env.DEPLOYMENT_FILE }} | kubectl apply -f -

      - name: Wait for rollout
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=5m